version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.14
      #KAFKA_ADVERTISED_LISTENERS: 192.168.0.14
      #KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_CREATE_TOPICS: "Dev:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_ADVERTISED_PORT: "9092"
  
    volumes:
      - /private/var/run/docker.sock:/var/run/docker.sock
